# bundle install
# bundle exec jekyll serve
#
# Due to https://github.com/rubygems/rubygems/issues/6272
# you may have to run `bundle install` as sudo.

source "https://rubygems.org"

# Theme
gem "minima", "~> 2.5"

# To upgrade: `bundle update github-pages`
gem "github-pages", group: :jekyll_plugins
